controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

configs:
  cm:
    accounts.admin: apiKey,login

server:
  config:
    initialAdminPassword: "bFeMUopbcvuG17Fc"
    admin.enabled: "true"
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
  ingress:
    enabled: false
  insecure: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true


