apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-ghcr-alkon
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ghcr.io/alkon
  type: helm
  name: ghcr-alkon-repo-name
  enableOCI: "true"
  username: alkon