# Kubernetes Provider
# provider "kubernetes" {
#   # Explicitly tell the Kubernetes provider to use the kubeconfig file
#   # generated by k3d after the cluster is created.
#   config_path = data.local_file.k3d_kubeconfig.filename
# }
#
# # Helm Provider
# provider "helm" {
#   # The Helm provider also needs Kubernetes access, so point it to the same config.
#   kubernetes {
#     config_path = data.local_file.k3d_kubeconfig.filename
#   }
# }

# You should also have other providers here, e.g.,
# provider "null" {} # If you are using null resources
# provider "external" {} # If you are using external data sources


terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.27"
    }

    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.17"
    }

    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14.0"
    }

    null = {
      source  = "hashicorp/null"
      version = ">= 3.2.0"
    }
  }
}

provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = "k3d-${var.k3d_cluster_name}"
}

provider "helm" {
  kubernetes {
    config_path    = "~/.kube/config"
    config_context = "k3d-${var.k3d_cluster_name}"
  }
}

provider "kubectl" {
  config_path    = "~/.kube/config"
  config_context = "k3d-${var.k3d_cluster_name}"
}
