apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: ${instrumentation_name} # templated variable
  namespace: ${namespace}      # templated variable
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_always_on
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest