apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: ${instrumentation_name}
  namespace: ${app_ns}
spec:
  exporter:
    endpoint: http://otel-collector-opentelemetry-collector.${collector_ns}.svc.cluster.local:4317
  python:
    volumeClaimTemplate: {}
    env:apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: ${instrumentation_name}
  namespace: ${app_ns}
spec:
  exporter:
    endpoint: http://otel-collector-opentelemetry-collector.${collector_ns}.svc.cluster.local:4317
  python:
    volumeClaimTemplate: {}
    env:
      - name: OTEL_PYTHON_AUTOLOAD_ENABLED
        value: "true"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_LOGS_EXPORTER
        value: "otlp"
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_PROPAGATORS
        value: "tracecontext,baggage"
      - name: OTEL_SERVICE_NAME
        value: "flask-app"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://otel-collector-opentelemetry-collector.otel-collector-ns:4317"
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: "grpc"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=k8s"

#      - name: OTEL_METRICS_EXPORTER
#        value: otlp
#      - name: OTEL_LOGS_EXPORTER
#        value: otlp
#      - name: OTEL_PROPAGATORS
#        value: tracecontext,baggage
#      - name: OTEL_TRACES_EXPORTER
#        value: otlp
#      - name: OTEL_SERVICE_NAME
#        value: ${otel_service_name}
#      - name: OTEL_EXPORTER_OTLP_ENDPOINT
#        value: http://otel-collector-opentelemetry-collector.${collector_ns}.svc.cluster.local:4317
