replicaCount: 2

image:
  repository: ghcr.io/alkon/flask-app # Updated to your full GHCR image path
  pullPolicy: IfNotPresent
  # REMOVED: 'tag: "latest"'. The deployment template will now default to Chart.AppVersion (1.0.0).

service:
  type: LoadBalancer #ClusterIP
  port: 5000
  targetPort: 5000

serviceAccount:
  create: false # in terraform apply: prevent Helm to re-create the ServiceAccount
  name: ""     # Leave empty to use the default generated name

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}

otel:
  enabled: true

# --- SEMI-AUTOMATED :) OTEL INJECTION ---
#otel:
#  enabled: true
#  env:
#    - name: OTEL_PYTHON_AUTOLOAD_ENABLED
#      value: "true"
#    - name: OTEL_METRICS_EXPORTER
#      value: "otlp"
#    - name: OTEL_LOGS_EXPORTER
#      value: "otlp"
#    - name: OTEL_TRACES_EXPORTER
#      value: "otlp"
#    - name: OTEL_PROPAGATORS
#      value: "tracecontext,baggage"
#    - name: OTEL_SERVICE_NAME
#      value: "flask-app"
#    - name: OTEL_EXPORTER_OTLP_ENDPOINT
#      value: "http://otel-collector-opentelemetry-collector.otel-collector-ns:4317"
#    - name: OTEL_EXPORTER_OTLP_PROTOCOL
#      value: "grpc"
#    - name: OTEL_RESOURCE_ATTRIBUTES
#      value: "deployment.environment=k8s"
