mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.128.0

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  exporters:
    debug: {}  # use debug instead of deprecated logging

  processors:
    batch: {}

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]  # match exporter name here
