mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.128.0

config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: "flask-app"
            static_configs:
              - targets: ["flask-app.flask-app-namespace.svc.cluster.local:5000"]

  exporters:
    prometheus:
      endpoint: "/metrics" #"0.0.0.0:8889"

  processors:
    batch: {}

  service:
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [batch]
        exporters: [prometheus]
